apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: frontend-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "update"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["frontend-tls"] 
    verbs: ["get", "update"]