apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-egress-restrict
spec:
  podSelector:
    matchLabels:
      io.kompose.service: backend-service
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              io.kompose.service: api-service