apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx
data:
  default.conf: |
    server {
      listen 80;

      location / {
        if ($http_x_forwarded_client_cert = "") {
            return 403 "Client certificate required.";
        }
        root /usr/share/nginx/html;
        index index.html;
      }

      location /api/ {
        if ($http_x_forwarded_client_cert = "") {
            return 403 "Client certificate required.";
        }
        proxy_pass http://api-service.default.svc.cluster.local:8081/api/v1/;
      }

      location /status/ {
        if ($http_x_forwarded_client_cert = "") {
            return 403 "Client certificate required.";
        }
        proxy_pass http://api-service.default.svc.cluster.local:8081/api/v1/status;
      }

      location /data {
        if ($http_x_forwarded_client_cert = "") {
            return 403 "Client certificate required.";
        }
        proxy_pass http://api-service.default.svc.cluster.local:8081/api/v1/data;

        proxy_set_header Host api-service.default.svc.cluster.local;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Content-Type $http_content_type;

        proxy_pass_request_body on;
        proxy_pass_request_headers on;
      }

      location /update {
        if ($http_x_forwarded_client_cert = "") {
            return 403 "Client certificate required.";
        }
        proxy_pass http://api-service:8081/api/v1/update;
      }
        
      location /delete {
        if ($http_x_forwarded_client_cert = "") {
            return 403 "Client certificate required.";
        }
        proxy_pass http://api-service:8081/api/v1/delete;
      }

      location = /healthz {
          access_log off;
          return 200 "OK";
      }
    }