name: CI

on: [push]


jobs:

  build:
    runs-on: ubuntu-latest
    steps: 
     - uses: actions/checkout@v4
     - run: |
        echo "Multiline"


  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - run: echo "pipeline radi"

  # dockerize:
  
  # lint:

  # deploy:
